### ISSUE TITLE
Jupyterlite demo

### ISSUE THREAD

**Issue by psychemedia** [Octoframes/jupyter_compare_view#18]
The simplest way to create a Jupyterlite demo requires access to a Python package on PyPi, or a prebuilt wheel that can be downloaded from the repo. 

You can build a wheel by running `pip3 wheel .` in the root directory. (It's perhaps most convenient to create a Github Action to create the wheel on a repo push and then commit it into the repo.)

`

**Comment by psychemedia** [comment]
Ah, just realised I can build and ship a local wheel as part of the distribution:

```bash
python -m pip wheel .
mkdir -p pypi
cp jupyter_splitview*.whl pypi/
```

**Comment by psychemedia** [comment]
Okay - running into dependency issues arising from package versions installed in pyodide.

`ValueError: Requested 'ipykernel>=6.13.0', but ipykernel==6.9.2 is already installed`

I relaxed the pinning on `ipykernel` in the `pyproject.toml` file but the higher version may be being asserted elsewhere and I don't have the time to go chasing version conflicts right now.

For reference, this is the action I'm using:

```yaml
name: Build and Deploy Jupyterlite Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install the dependencies
        run: |
          python -m pip install -r .binder/requirements.txt
          python -m pip install -r .jupyterlite/requirements.txt
          python -m pip wheel .
          mkdir -p pypi
          cp jupyter_splitview*.whl pypi/
      - name: Build the JupyterLite site
        run: |
          mkdir -p content
          cp README.md content
          cp example_notebook.ipynb content
          jupyter lite build --contents ./content
      - name: Upload (dist)
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./_output

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
```

It also pulls on a file `.jupyterlite/requirements.txt`:

```text
#------ JupyerLite install -------
jupyterlite==0.1.0b8

#------ JupyerLab install -------
ipywidgets>=7.7,<8
@ -9,4 +9,4 @@ jupyterlab-language-pack-fr-FR
jupyterlab-language-pack-zh-CN

#------- Demo install -------
# Reuse .binder/requierments.txt
# Reuse .binder/requirements.txt
```

You'd also need to activate Github Pages to build from root on `gh-pages` branch.

In the notebook, you'd need to:

```python
import micropip
await micropip.install("jupyter-splitview")
```

Or in a guarded way for a generic notebook:

```python
import platform as p

if p.machine()=="wasm32":
    import micropip
    await micropip.install("jupyter-splitview")
```

You should then be able to open into the demo notebook w/ a URL of the form:

https://kolibril13.github.io/jupyter-splitview/lab/index.html?path=example_notebook.ipynb
